version: "3.1"
services:
  # base - ubuntu with zsh
  ubuntu:
    container_name: ubuntu
    image: taoxuau/ubuntu:22.04.${ARCH}
    platform: linux/${ARCH}
    build:
      context: .
      platforms:
        - linux/${ARCH}
      dockerfile: Dockerfile.ubuntu
      args:
        # Use default value in Dockerfile, or specify your value here
        - ARCH=${ARCH}
        - USER=${DEFAULT_USER}
        - P10KZSH=${P10KZSH}

  # base - almalinux with zsh
  almalinux:
    container_name: almalinux
    image: taoxuau/almalinux:8.${ARCH}
    platform: linux/${ARCH}
    build:
      context: .
      platforms:
        - linux/${ARCH}
      dockerfile: Dockerfile.almalinux
      args:
        - ARCH=${ARCH}
        - USER=${DEFAULT_USER}
        - P10KZSH=${P10KZSH}

  # java
  # devcon_java:
  #   image: taoxuau/devcon:2021.java
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.devcon
  #     args:
  #       - JAVA=8,11
  #   volumes:
  #     - ~/.ssh/id_rsa:/home/devops/.ssh/id_rsa
  #     - ~/.ssh/id_rsa.pub:/home/devops/.ssh/id_rsa.pub

  # nodejs
  # devcon_node:
  #   image: taoxuau/devcon:2021.node
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.devcon
  #     args:
  #       - NODE=12.22.5, 14.17.5
  #   volumes:
  #     - ~/.ssh/id_rsa:/home/devops/.ssh/id_rsa
  #     - ~/.ssh/id_rsa.pub:/home/devops/.ssh/id_rsa.pub

  # ruby
  ruby:
    container_name: ruby
    image: taoxuau/devcon:ruby.2023.${ARCH}
    platform: linux/${ARCH}
    build:
      context: .
      platforms:
        - linux/${ARCH}
      dockerfile: Dockerfile.devcon
      args:
        - ARCH=${ARCH}
        - RUBY=3.1.4, 2.7.8
    volumes:
      - ~/.ssh/id_rsa:/home/devops/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/home/devops/.ssh/id_rsa.pub

  # python
  # devcon_python:
  #   image: taoxuau/devcon:2021.python
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.devcon
  #     args:
  #       - PYTHON=3.9.7, 3.8.12
  #   volumes:
  #     - ~/.ssh/id_rsa:/home/devops/.ssh/id_rsa
  #     - ~/.ssh/id_rsa.pub:/home/devops/.ssh/id_rsa.pub
