version: "3.1"
services:
  devcon:
    image: taoxuau/devcon:2021
    build:
      context: .
      args:
        - USER=devops
        - P10KZSH=https://raw.githubusercontent.com/taoxuau/devcon/master/default-confs/p10k.zsh
        - RUBY=2.7.4
        # - PYTHON=3.9.6
        - NODE=14.17.5
    volumes:
      # mapping ssh key
      - ~/.ssh/id_rsa:/home/devops/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/home/devops/.ssh/id_rsa.pub
