FROM ubuntu:20.04

# install essential packages
RUN set -ex \
  && apt-get update \
  && apt-get upgrade --yes \
  && apt-get install --yes dumb-init \
  && apt-get clean

# keep container running - https://stackoverflow.com/a/42873832/629950
CMD ["tail", "-f", "/dev/null"]

# https://github.com/Yelp/dumb-init
ENTRYPOINT ["dumb-init", "--"]
