version: "3.1"
services:
  # base - ubuntu with zsh
  ubuntu:
    image: taoxuau/ubuntu:20.04
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
      args:
        # Use default value in Dockerfile, or specify your value here
        - USER=devops
        - P10KZSH=https://raw.githubusercontent.com/taoxuau/devcon/master/default-confs/p10k.zsh

  # java
  devcon_java:
    extends: ubuntu
    image: taoxuau/devcon:2021.java
    build:
      context: .
      dockerfile: Dockerfile.devcon
      args:
        - JAVA=8,11
    volumes:
      - ~/.ssh/id_rsa:/home/devops/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/home/devops/.ssh/id_rsa.pub

  # nodejs
  devcon_node:
    image: taoxuau/devcon:2021.node
    build:
      context: .
      dockerfile: Dockerfile.devcon
      args:
        - NODE=14.17.5
    volumes:
      - ~/.ssh/id_rsa:/home/devops/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/home/devops/.ssh/id_rsa.pub

  # ruby
  devcon_ruby:
    image: taoxuau/devcon:2021.ruby
    build:
      context: .
      dockerfile: Dockerfile.devcon
      args:
        - RUBY=2.7.4
    volumes:
      - ~/.ssh/id_rsa:/home/devops/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/home/devops/.ssh/id_rsa.pub

  # python
  devcon_python:
    image: taoxuau/devcon:2021.python
    build:
      context: .
      dockerfile: Dockerfile.devcon
      args:
        - PYTHON=3.9.6
    volumes:
      - ~/.ssh/id_rsa:/home/devops/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/home/devops/.ssh/id_rsa.pub
